-- ejemplos 

Create or replace procedure sp_mensaje 
as
BEGIN
    --Mostramos un mensaje
    dbms_output.put_line('Hoy es juernes con música  ');
end; 

-- llamada al procedimiento

Begin 
   sp_mensaje;
End; 

--PROCEDIMIENTO CON BLOQUE PL/SQL
CREATE OR REPLACE PROCEDURE SP_EJEMPLO_PLSQL
AS   
BEGIN
DECLARE 
    V_NUMERO NUMBER;
BEGIN
V_NUMERO:= 14;
IF V_NUMERO > 0 THEN    
DBMS_OUTPUT.PUT_LINE(' POSITIVO');

ELSE  
DBMS_OUTPUT.PUT_LINE('NEGATIVO');
END IF; 

END;
END;

BEGIN
    SP_EJEMPLO_PLSQL;

END;

--OTRA SINTAXIS PARA TENER VARIABLES DENTRO DE UN PROCEDIMIENTO
-- NO SE UTILIZA LA PALABRA DECLARE

CREATE OR REPLACE PROCEDURE SP_EJEMPLO_PLSQL2
AS
    V_NUMERO NUMBER:=14;
BEGIN
    
    IF V_NUMERO > 0 THEN    
       DBMS_OUTPUT.PUT_LINE(' POSITIVO');

    ELSE  
       DBMS_OUTPUT.PUT_LINE('NEGATIVO');
    
    END IF; 

END;

BEGIN
    SP_EJEMPLO_PLSQL2;

END;

--PROCEDIMIENTO PARA SUMAR DOS NUMEROS

CREATE OR REPLACE PROCEDURE SP_SUMAR_NUMEROS
(P_NUMERO1 NUMBER, P_NUMERO2 NUMBER)
AS  
   V_SUMA NUMBER;  
BEGIN 
    V_SUMA:= P_NUMERO1 + P_NUMERO2;
    DBMS_OUTPUT.PUT_LINE('LA SUMA DE ' || P_NUMERO1|| ' + ' || P_NUMERO2 || ' ES IGUAL A '|| V_SUMA);

END; 

BEGIN 
    SP_SUMAR_NUMEROS(5,6);
END;

--NECESITO UN PROCEDIMIENTO PARA DIVIDIR DOS NUMEROS
--SE LLAMARA SP_DIVIDIR_NUMEROS

CREATE OR REPLACE PROCEDURE SP_DIVIDIR_NUMEROS
(P_NUMERO1 NUMBER, P_NUMERO2 NUMBER) 
AS  
    V_DIVIDE NUMBER;
BEGIN
    DECLARE 
    V_DIVIDE NUMBER;
    BEGIN 
     V_DIVIDE:= P_NUMERO1 / P_NUMERO2;  
    DBMS_OUTPUT.PUT_LINE('LA DIVISION DE ' || P_NUMERO1|| ' Y ' || P_NUMERO2 || ' ES IGUAL A '|| V_DIVIDE); 
EXCEPTION
      WHEN ZERO_DIVIDE THEN    
          DBMS_OUTPUT.PUT_LINE('DIVISION ENTRE CERO PROCEDURE INNER');
END; 
    EXCEPTION
     WHEN ZERO_DIVIDE THEN    
          DBMS_OUTPUT.PUT_LINE('DIVISION ENTRE CERO PROCEDURE');

END; 

BEGIN 
    SP_DIVIDIR_NUMEROS(8,0);
EXCEPTION 
     WHEN ZERO_DIVIDE THEN
        DBMS_OUTPUT.PUT_LINE('DIVISION ENTRE CERO PROCEDURE, PL/SQL ');
END;


